// angular/src/app.component.ts
import { Component } from "@angular/core";
import { FeedClipAngularComponent } from "@feedclip/sdk/angular";
import { createIndexedDbFeedbackStore } from "@feedclip/sdk";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [FeedClipAngularComponent],
  template: `
    <main class="demo-shell">
      <section class="demo-copy">
        <a class="brand-link" href="https://www.feedclip.dev" target="_blank" rel="noreferrer">
          <span class="brand-mark" aria-hidden="true">
            <span class="brand-dot"></span>
          </span>
          feedclip
        </a>
        <span class="eyebrow">Angular 21 example</span>
        <h1>Drop video feedback into an Angular product.</h1>
        <p>
          The standalone adapter handles mount, config updates, and cleanup.
          Submissions stay in local IndexedDB.
        </p>
        <ul>
          <li>No account or backend required</li>
          <li>Standalone Angular component</li>
          <li>Strict TypeScript configuration</li>
        </ul>
      </section>

      <feedclip-widget [config]="config" />
    </main>
  `,
})
export class AppComponent {
  readonly config = {
    locale: "en-US" as const,
    maxDurationMilliSeconds: 60_000,
    maxFileSize: 100_000_000,
    defaultVideoFileExtension: "webm" as const,
    defaultVideoFileNameStyle: "ISO 8601" as const,
    privacyNotice: {
      url: "https://github.com/andreyshedko/feedclip",
      label: "How this demo handles data",
    },
    getContext: () => ({
      source: "angular-stackblitz-example",
      plan: "demo",
    }),
    onSubmit: createIndexedDbFeedbackStore({
      databaseName: "feedclip-angular-free-example",
    }),
  };
}

// react-pro/src/App.tsx
import { useEffect, useState } from "react";
import FeedClip, {
  createIndexedDbFeedbackStore,
  type FeedClipLicenseConfig,
} from "@feedclip/sdk";
import "@feedclip/sdk/style.css";
import { loadDemoLicense } from "./license";

const saveLocally = createIndexedDbFeedbackStore({
  databaseName: "feedclip-react-pro-example",
});

export default function App() {
  const [license, setLicense] = useState<FeedClipLicenseConfig>();
  const [licenseError, setLicenseError] = useState("");

  useEffect(() => {
    const controller = new AbortController();
    void loadDemoLicense(controller.signal).then(setLicense).catch((error: unknown) => {
      if (controller.signal.aborted) return;
      setLicenseError(error instanceof Error ? error.message : "Pro demo is unavailable");
    });
    return () => controller.abort();
  }, []);

  return (
    <main className="demo-shell">
      <section className="demo-copy">
        <a className="brand-link" href="https://www.feedclip.dev" target="_blank" rel="noreferrer">
          <span className="brand-mark" aria-hidden="true">
            <span className="brand-dot" />
          </span>
          feedclip
        </a>
        <span className="eyebrow">FeedClip Pro · React 19</span>
        <h1>Polished feedback capture on your own infrastructure.</h1>
        <p>
          Pro unlocks trimming, thumbnails, upload progress, and branding
          removal. This demo keeps submissions locally in IndexedDB.
        </p>
        <ul>
          <li>Temporary 15-minute demo license</li>
          <li>No permanent license in source code</li>
          <li>Your backend and storage remain yours</li>
        </ul>
        {licenseError && <p role="alert">{licenseError}</p>}
      </section>

      {license ? (
        <FeedClip
          config={{
            locale: "en-US",
            maxDurationMilliSeconds: 60_000,
            maxFileSize: 100_000_000,
            defaultVideoFileExtension: "webm",
            defaultVideoFileNameStyle: "ISO 8601",
            license,
            onLicenseError: setLicenseError,
            getContext: () => ({ source: "react-pro-stackblitz", plan: "pro" }),
            onSubmit: saveLocally,
          }}
        />
      ) : (
        <section className="feedclip-shell" aria-live="polite">
          <p>{licenseError || "Loading temporary Pro license…"}</p>
        </section>
      )}
    </main>
  );
}
